app/__init__.py
from flask import Flask
from .routes import main_bp

def create_app():
    app = Flask(__name__)
    app.register_blueprint(main_bp)
    
    return app

app/routes.py
from flask import Blueprint, jsonify, render_template, redirect, url_for
from .pokeneas import POKENEAS
import random
import os
import socket

main_bp = Blueprint('main', __name__)

def get_container_id():
    try:
        # Intentar obtener el nombre del host usando socket
        return socket.gethostname()
    except AttributeError:
        return os.uname()[1]

def generate_pokenea_data(pokenea):
    """Genera el diccionario con la información del pokenea."""
    return {
        'id': pokenea['id'],
        'nombre': pokenea['nombre'],
        'altura': pokenea['altura'],
        'habilidad': pokenea['habilidad'],
        'container_id': get_container_id(),
        'frase_filosofica': pokenea['frase_filosofica'],
    }

@main_bp.route('/')
def index_redirect():
    return redirect(url_for('main.display_pokenea'))

@main_bp.route('/json')
def get_pokenea_json():
    pokenea = random.choice(POKENEAS)
    return jsonify(generate_pokenea_data(pokenea))

@main_bp.route('/index')
def display_pokenea():
    pokenea = random.choice(POKENEAS)
    return render_template('index.html', pokenea=pokenea, container_id=get_container_id())

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <title>Pokeneas</title>
  </head>
  <body>
    <div class="container">
      <h1>{{ pokenea.nombre }}</h1>
      <img src="{{ pokenea.imagen }}" alt="{{ pokenea.nombre }}" />
      <p><b>Frase filosófica: </b> {{pokenea.frase_filosofica }}</p>
      <p><b>Habilidad: </b> {{ pokenea.habilidad }}</p>
      <p><b>Altura: </b> {{ pokenea.altura }} m</p>
      <p><b>Container ID: </b>{{ container_id }}</p>
      <div class="random-img">
        <img
          id="random_pokemon_image_url_id"
          src="{{ url_for('static', filename='random.png') }}"
          alt="Random Pokemon Click Here"
          onclick="location.reload();"
        />
        <h2>Random</h2>
      </div>
      <button class="top-left-button" onclick="window.location.href='{{ url_for('main.get_pokenea_json') }}';">Acceder a JSON</button>    </div>
  </body>
</html>